version: 0.1

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm run build
  post_build:
    commands:
      - aws s3 sync --delete build s3://bamboolemur.com --cache-control max-age=3600
