version: 0.1

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm run build
artifacts:
  files:
    - build/**/*
    - discard-paths: yes
